#ifndef BOARD_H_
#define BOARD_H_

// Tracing
#define DEBUG_REACTOR_IDLE IOPORT_CREATE_PIN(PORTA, 3)
#define DEBUG_REACTOR_BUSY IOPORT_CREATE_PIN(PORTA, 5)

#define ALERT_OUTPUT_PIN  IOPORT_CREATE_PIN(PORTB, 2)


#endif /* BOARD_H_ */